### PR TITLE
alv-grid-merge-cells

### PR DESCRIPTION
**Pull request by RTagliento**
As reuqested....

I merged the method of this project 
https://github.com/tricktresor/alv-grid-merge-cells

I just ADDED without any problem the 5 method of ZTRCKTRSR_GUI_ALV_GRID_MERGE to ZCL_FAVL

Z_DISPLAY Instance Method Public
Z_INIT_CELL_STYLES Instance Method Public
Z_SET_CELL_STYLE Instance Method Public
Z_SET_FIXED_COL_ROW Instance Method Public
Z_SET_MERGE_HORIZ Instance Method Public
Z_SET_MERGE_VERT Instance Method Public

### CODE REVIEW

**Comment by fidley** [comment]
Hi @RTagliento, 
I looked on this PR and for me it is reasonable to rewrite the code a bit, to not have two different display methods. I'll try to make it this week.
Cheers
Łukasz

**Comment by RTagliento** [comment]
That sound great and good ... I am Happy.

Thank you.

**Comment by SantiMorenoSAP** [comment]
You are all big!

**Comment by RTagliento** [comment]
Great!

Tomorrow I will use soon this new version! 😄

**Comment by RTagliento** [comment]
It is working and I am in progress.... thank you a lot!

horizontal merge works.....

next step vertical merge and DROPDOWN

image

**Comment by fidley** [comment]
Looks like an Excel file 😁

**Comment by RTagliento** [comment]
vertical merge is ok.... dropdown too ;)

image

**Comment by fidley** [comment]
Perfect, thanks a lot!

**Comment by fidley** [comment]
As far as I know, word wrap is not allowed in grid cells. I've never seen it and never seen the variables or methods that would allow that in ALV Grid or Tree.

**Comment by RTagliento** [comment]
Thanks about this confirmation. ;)

**Pull request closed without merging**
