### PR TITLE
Update zcl_falv.clas.abap

### PR DESCRIPTION
**Pull request by mamuduruvenkatesh**
Hello  Fidley,

This is pull request for the issue described in - https://github.com/fidley/falv/issues/68,
We have implemented this and it's working fine from some time. Hence, we would like to propose this change into our FALV repository to avoid the issue of setting default layout when we have multiple layouts in same ALV.

Request you, please review and if it looks fine please accept the PR.

With regards,
Venkatesh

### CODE REVIEW

**Comment by fidley** [comment]
Hi Venkatesh, 
seems something is still missing here. I can see only adaptation of the Create method interface, nothing more. Could you please check?
Cheers
Łukasz

**Comment by mamuduruvenkatesh** [comment]
Hi Lukasz,

When we have multiple ALVs in same screen we need additional parameter to differentiate respective ALV layout . Hence we added optional parameter (I_HANDLE) for method CREATE. 

While calling this method we would need to pass unique value foe each section of ALV Let's say "ALV1" and "ALV2" etc. This is the only change that we are prosping, nothing more.

With this we will not be having the issue while setting default layout for each section.

Best Regards,
Venkatesh

**Comment by fidley** [comment]
I understand the approach but this variable is not used inside the CREATE method, could you please check the code which is in the commit?

**Comment by mamuduruvenkatesh** [comment]
Apologies for this, it's my mistake. 

Now I have added missing code lines.

Kind regards,
Venkatesh

**Comment by fidley** [comment]
Perfect. Thanks ;)

**Pull request merged**
